export enum PlayerLifecycle {
  STOPPED = 'STOPPED',
  REGISTERING = 'REGISTERING',
  REGISTERED = 'REGISTERED',
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  DISCONNECTING = 'DISCONNECTING',
  DISCONNECTED = 'DISCONNECTED',
}

export const NONE = 'NONE'
