name: Deploy On PR

on:
  push:
    branches-ignore:
      - main

jobs:
  ci:
    uses: ./.github/workflows/shared.pre_job.yml
    with:
      on_branch: 'true'
    secrets: inherit

  cd:
    needs: [ci]
    if: needs.pre_ci.outputs.should_skip != 'true'
    uses: ./.github/workflows/shared.do-deploy.yml
    secrets: inherit
