#file: noinspection YAMLSchemaValidation
name: Deploy
on: [ push ]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: "client:build"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: cd packages/client && npm i && npm run build

      - name: checks
      - uses: maximousblk/setup-deno@v2
      - run: cd packages/server && deno fmt --check
      - run: cd packages/server && deno lint
      - run: cd packages/server && deno task test

  check:
    name: Deployment Check
    needs: ci
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.early.outputs.status }}
    steps:
      - name: Check Deployability
      - uses: actions/checkout@v3
      - uses: maximousblk/setup-deno@v2
      - id: early
        run: ./tools/check.sh

  deploy:
    name: Deploy
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.status == 'deploy'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: "build:client"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: cd packages/client && npm i && npm run build

      - name: "build:server"
        uses: maximousblk/setup-deno@v2
      - run: cd packages/server && deno task build

      - name: "Upload to Deno Deploy"
        uses: denoland/deployctl@v1
        with:
          project: zenwork-privatus
          entrypoint: "main.ts"
          root: "./packages/server"
