#file: noinspection YAMLSchemaValidation
name: Deploy
on: [ push ]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 19
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "~1.32"

      - name: install:common
        run: cd packages/common && yarn

      - name: install:client
        run: cd packages/client && yarn

      - name: check:server:format
        run: cd packages/server && deno fmt --check .
      - name: check:server:lint
        run: cd packages/server && deno lint .
      - name: check:client:lint&format
        run: cd packages/client && yarn run check
      - name: build:common
        run: cd packages/common && yarn run build
      - name: build:client
        run: cd packages/client && yarn run build
      - name: test:client
        run: cd packages/client && yarn run test
      - name: test:server
        run: cd packages/server && deno task test

  check:
    name: Should Deploy
    needs: ci
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.early.outputs.status }}
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "~1.32"

      - name: Run Script
        id: early
        run: ./tools/check.sh

  deploy:
    name: CD
    needs: check
    runs-on: ubuntu-latest
    # deploy only if changesets have been released
    if: needs.check.outputs.status == 'deploy'
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 19
      - uses: maximousblk/setup-deno@v2

      - name: build client
        run: cd packages/client && yarn && yarn run deploy && yarn run clean

      - name: deploy
        uses: denoland/deployctl@v1
        with:
          project: zenwork-privatus
          entrypoint: "server/main.ts"
          root: "./packages"
