name: Deploy On Main

on:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  pre_job:
    name: pre_job
    uses: ./.github/workflows/shared.pre_job.yml
    secrets: inherit

  ci:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    uses: ./.github/workflows/shared.ci.yml
    secrets: inherit

  check:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    uses: ./.github/workflows/shared.should-deploy.yml
    secrets: inherit

  deploy:
    needs: [ ci, check ]
    if: needs.pre_job.outputs.should_skip != 'true'
    uses: ./.github/workflows/shared.do-deploy.yml
    secrets: inherit
