name: CI/CD [ON MAIN]

on:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:

  check:
    name: Check Unmerged Changesets
    runs-on: ubuntu-latest
    outputs:
      deployable: ${{ steps.check.outputs.deployable }}
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ inputs.deno-version }}

      - name: find changesets
        id: check
        run: ./tools/check.sh

  ci:
    needs: [check]
    if: |
      needs.check.outputs.deployable == 'true' &&
      github.event_name == 'pull_request' && 
      github.event.action == 'closed' && 
      github.event.pull_request.merged == true
    uses: ./.github/workflows/shared.ci.yml
    secrets: inherit

  cd:
    needs: [ci]
    if: needs.pre_ci.outputs.should_skip != 'true'
    uses: ./.github/workflows/shared.cd.yml
    secrets: inherit
