name: Deploy
on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.early.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Deployability
        uses: maximousblk/setup-deno@v2
      - id: early
        run: ./tools/check.sh

  deploy:
    name: Deploy
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.status == 'deploy'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build client
        uses: maximousblk/setup-deno@v2

      - run: cd packages/server && deno task build && deno task test && ls dist

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: zenwork-privatus
          entrypoint: "main.ts"
          root: "./packages/server"
