name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build client
        uses: maximousblk/setup-deno@v2

      - run: cd packages/server && deno task build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: zenwork-privatus
          entrypoint: "./packages/server/main.ts"


#jobs:
#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    if: github.event_name == 'release' && github.event.action == 'created'
#    permissions:
#      id-token: write
#      contents: read
#
#    steps:
#      - name: Clone repository
#        uses: actions/checkout@v3
#
#      - name: Install dependencies
#        run: npm ci
#
#      - name: Build Astro
#        run: npm run build
#
#      - name: Upload to Deno Deploy
#        uses: denoland/deployctl@v1
#        with:
#          project: zenwork-privatus
#          entrypoint: server/entry.mjs
#          root: dist
