#file: noinspection YAMLSchemaValidation
name: Deploy
on: [ push ]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "~1.32"

      - name: build
        run: cd packages/client && npm i && npm run build

      - name: check:format
        run: cd packages/server && deno fmt --check
      - name: check:lint
        run: cd packages/server && deno lint
      - name: check:tests
        run: cd packages/server && deno task test

  check:
    name: Deployment Check
    needs: ci
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.early.outputs.status }}
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "~1.32"

      - name: Run Script
        id: early
        run: ./tools/check.sh

  deploy:
    name: Deploy
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.status == 'deploy'
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: maximousblk/setup-deno@v2

      - name: Setup Node
        run: cd packages/client && npm i && npm run build

      - name: Deploy
        uses: denoland/deployctl@v1
        with:
          project: zenwork-privatus
          entrypoint: "main.ts"
          root: "./packages/server"
