name: Deploy PR

on:
  push:
    branches-ignore:
      - main

jobs:
  pre_job:
    name: pre_job
    uses: ./.github/workflows/pre_job.yml
    secrets: inherit

  ci:
    name: CI
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 19
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "~1.36"

      - name: install:common
        run: cd packages/common && yarn

      - name: install:client
        run: cd packages/client && yarn

      - name: check:server:format
        run: cd packages/server && deno fmt --check .
      - name: check:server:lint
        run: cd packages/server && deno lint .
      - name: check:client:lint&format
        run: cd packages/client && yarn run check
      - name: build:common
        run: cd packages/common && yarn run build
      - name: build:client
        run: cd packages/client && yarn run build
      - name: test:client
        run: cd packages/client && yarn run test
      - name: test:server
        run: cd packages/server && deno task test

  check:
    name: Check if should deploy
    needs: pre_job
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ steps.check.outputs.deploy }}
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "~1.36"

      - name: Run Script
        id: check
        run: ./tools/check.sh

  deploy:
    name: Deploy
    needs: [ci, check]
    runs-on: ubuntu-latest
    # deploy only if changesets have been released
    if: needs.check.outputs.deploy == 'true'
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 19
      - uses: maximousblk/setup-deno@v2

      - name: build common
        run: cd packages/common && yarn && yarn run clean

      - name: build client
        run: cd packages/client && yarn && yarn run build && yarn run clean

      - name: build server
        run: cd packages/server

      - name: deploy
        uses: denoland/deployctl@v1
        with:
          project: zenwork-privatus
          root: "./packages/"
          entrypoint: "server/main.ts"
          import-map: "server/import_map.json"
