name: Deploy
on: [push]

jobs:
  check:
    outputs:
      status: ${{ steps.early.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: early
        name: Deployable Check
        run: ./tools/check.sh
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: needs.check.outputs.status == 'deploy' && !startsWith(github.ref, 'refs/tags')
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build client
        uses: maximousblk/setup-deno@v2

      - run: deno task checkDeployable
      - run: cd packages/server && deno task build && deno task test && ls dist

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: zenwork-privatus
          entrypoint: "main.ts"
          root: "./packages/server"
