name: CI/CD

on:
  push:
    branches-ignore:
      - main

jobs:
  ci:
    uses: ./.github/workflows/shared.ci.yml
    with:
      on_branch: 'true'
    secrets: inherit

  cd:
    needs: [ci]
    if: needs.ci.outputs.should_skip != 'true'
    uses: ./.github/workflows/shared.cd.yml
    secrets: inherit
