name: Release

on:
#  pull_request:
#    types:
#      - closed
  push:
    branches:
      - main

jobs:
  release:
    name: GH Release
#    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'Version Packages')
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: faker/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: xz
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
