name: Release

on:
#  pull_request:
#    types:
#      - closed
  push:
    branches:
      - main

jobs:
  release:
    name: GH Release
#    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'Version Packages')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Authenticate with GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create GitHub Release
        run: |
          gh release create \
            "v${{ github.event.pull_request.merged_commit_sha }}" \
            --title "Release v${{ github.event.pull_request.merged_commit_sha }}" \
            --notes "Release notes for v${{ github.event.pull_request.merged_commit_sha }}" \
            --repo ${{ github.repository }} \
            --target ${{ github.event.pull_request.merge_commit_sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
