name: Release

on:
#  pull_request:
#    types:
#      - closed
  push:
    branches:
      - main

jobs:
  release:
    name: GH Release
#    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'Version Packages')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release.tar.gz,foo/*.txt"
          bodyFile: "body.md"
