name: Release

on:
#  pull_request:
#    types:
#      - closed
  push:
    branches:
      - main

jobs:
  release:
    name: GH Release
#    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'Version Packages')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install the gh cli
        uses: ksivamuthu/actions-setup-gh-cli@v2
        with:
          version: 2.24.3

      - name: Create GitHub Release
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh release create \
            "v${{ github.event.pull_request.merged_commit_sha }}" \
            --title "Release v${{ github.event.pull_request.merged_commit_sha }}" \
            --notes "Release notes for v${{ github.event.pull_request.merged_commit_sha }}" \
            --repo ${{ github.repository }} \
            --target ${{ github.event.pull_request.merge_commit_sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
