name: Should Deploy Test

on:
  workflow_call:

    inputs:
      deno-version:
        type: string
        required: false
        default: '~1.36'

    outputs:
      deploy:
        value: ${{ jobs.check.outputs.deploy }}

jobs:
  check:
    name: Test for existance of unmerged changesets
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ steps.check.outputs.deploy }}
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ inputs.deno-version }}

      - name: Run Script
        id: check
        run: ./tools/check.sh
