name: Pre Job Check

on:
  workflow_call:

    inputs:
      on_branch:
        type: string
        required: true
        default: 'false'

    outputs:
      should_skip:
        value: ${{ jobs.pre_job.outputs.should_skip }}

jobs:
  pre_job:
    name: Job Pre-Checks to Skip Workflow
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || ${{ inputs.on_branch == 'true'}}
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/README.md"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
